// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-departments.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_departments_default = defineTool({
  name: "list_my_departments",
  title: "List my departments",
  description: "Lista os departamentos da igreja em que o usu\xE1rio autenticado participa (como l\xEDder ou volunt\xE1rio).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("department_members").select("role, departments:department_id(id, name, church_id, created_at)").eq("user_id", ctx.getUserId());
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { departments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-schedules.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_schedules_default = defineTool2({
  name: "list_my_upcoming_schedules",
  title: "List my upcoming schedules",
  description: "Lista as pr\xF3ximas escalas (schedules) do usu\xE1rio autenticado, ordenadas por data.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("M\xE1ximo de escalas a retornar (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("schedules").select("id, date, time_start, time_end, department_id, assignment_role, notes").eq("user_id", ctx.getUserId()).gte("date", today).order("date", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { schedules: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_announcements_default = defineTool3({
  name: "list_department_announcements",
  title: "List department announcements",
  description: "Lista os avisos do mural de um departamento em que o usu\xE1rio autenticado participa.",
  inputSchema: {
    department_id: z2.string().uuid().describe("ID do departamento."),
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ department_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("announcements").select("id, title, content, created_at, created_by").eq("department_id", department_id).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { announcements: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zuksvsxnchwskqytuxxq";
var mcp_default = defineMcp({
  name: "levi-escalas-mcp",
  title: "LEVI Escalas",
  version: "0.1.0",
  instructions: "Ferramentas do LEVI (leviescalas.com.br) para consultar escalas, departamentos e avisos da igreja do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_departments_default, list_my_schedules_default, list_announcements_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
